version: '3.8'

services:
  app:
    build: .
    ports:
      - "9092:9092"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/online_banking
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - db
    networks:
      - my-network
    volumes:
      - app-data:/app/data

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: online_banking
    ports:
      - "3307:3306"
    networks:
      - my-network
    volumes:
      - db-data:/var/lib/mysql

networks:
  my-network:
    driver: bridge

volumes:
  app-data:
    driver: local
  db-data:
    driver: local
